[env:waveshare-amoled]
platform = espressif32 @ ^6.5
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB
board_build.partitions = no_ota_8mb.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi

build_src_filter = +<*> +<buddies/> +<hw/> -<main.cpp.m5stick.bak> -<buddy.cpp> -<buddies/> -<character.cpp> -<ble_bridge.cpp> -<xfer.h>
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DXPOWERS_CHIP_AXP2101

lib_deps =
    moononournation/GFX Library for Arduino
    lewisxhe/XPowersLib
    lewisxhe/SensorLib
    adafruit/Adafruit BusIO
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    h2zero/NimBLE-Arduino @ ^1.4
